#!/bin/bash
echo "This will run on sharing.io humacs init"
echo "~/.sharing.io/init START"

# Override in your forks
export TMATE_SOCKET="${TMATE_SOCKET:-/tmp/ii.default.target.iisocket}"

cat <<EOF >> ~/.bashrc
function git-status-all {
    for d in \$(find \$HOME -name .git); do
        echo -e "\n*** Repository: \$d ***"
        git --git-dir=\$d --work-tree=\$d/.. status
    done
}
EOF

(
    set -a
    . /etc/os-release
    [ "$ID_LIKE" = "debian" ] && \
      sudo apt update
) &

if [ -f /var/run/secrets/kubernetes.io/serviceaccount/namespace ]; then
    echo "~/.sharing.io/init Waiting for tmate socket: $TMATE_SOCKET"
    /usr/local/bin/tmate-wait-for-socket.sh
    echo "~/.sharing.io/init Creating tmate SHELL window"
    # without it, there is only emacs, hard for new users
    tmate -F -v -S $TMATE_SOCKET new-window -d -c "$PWD" -n SHELL bash
    # Feel free to customize the startup beyond here
    if [ -f "users/${SHARINGIO_PAIR_USER:-$USER}-init" ] ; then
      ./users/${SHARINGIO_PAIR_USER:-$USER}
    fi
fi
