#!/bin/bash
echo "This will run on sharing.io humacs init"
echo "~/.sharing.io/init START"

cd $(dirname $0)
GIT_ROOT=$(git rev-parse --show-toplevel)
cd $GIT_ROOT

# Override in your forks
export TMATE_SOCKET="${TMATE_SOCKET:-/tmp/ii.default.target.iisocket}"

cat <<EOF >> ~/.bashrc
function git-status-all {
    for d in \$(find \$HOME -name .git); do
        echo -e "\n*** Repository: \$d ***"
        git --git-dir=\$d --work-tree=\$d/.. status
    done
}
EOF

echo "~/.sharing.io/init Waiting for tmate socket: $TMATE_SOCKET"
/usr/local/bin/tmate-wait-for-socket.sh

(
    set -a
    . /etc/os-release
    [ "$ID_LIKE" = "debian" ] && \
      sudo apt update
) &

if [ -x "$GIT_ROOT/users/${SHARINGIO_PAIR_USER:-$USER}-init" ] ; then
    (
        cd $INIT_DEFAULT_REPOS_FOLDER
        $GIT_ROOT/users/${SHARINGIO_PAIR_USER:-$USER}-init &
    )
fi

echo "~/.sharing.io/init Creating tmate SHELL window"
# without it, there is only emacs, hard for new users
tmate -F -v -S $TMATE_SOCKET new-window -d -c "$PWD" -n SHELL bash
# Feel free to customize the startup beyond here
